# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sleep\OneDrive\Documents\shotgun\mastertemplate\install\git\lazy_siouxsie\python\app\ui\lazy_siouxsie_ui.ui'
#
# Created: Sat Jun 30 00:49:42 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_lazySiouxsie(object):
    def setupUi(self, lazySiouxsie):
        lazySiouxsie.setObjectName("lazySiouxsie")
        lazySiouxsie.resize(400, 327)
        self.verticalLayout = QtGui.QVBoxLayout(lazySiouxsie)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtGui.QLabel(lazySiouxsie)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.file_label = QtGui.QLabel(lazySiouxsie)
        self.file_label.setObjectName("file_label")
        self.horizontalLayout_5.addWidget(self.file_label)
        self.file_path = QtGui.QLineEdit(lazySiouxsie)
        self.file_path.setObjectName("file_path")
        self.horizontalLayout_5.addWidget(self.file_path)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hdri_label = QtGui.QLabel(lazySiouxsie)
        self.hdri_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.hdri_label.setObjectName("hdri_label")
        self.horizontalLayout.addWidget(self.hdri_label)
        self.hdriList = QtGui.QListWidget(lazySiouxsie)
        self.hdriList.setAlternatingRowColors(True)
        self.hdriList.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.hdriList.setObjectName("hdriList")
        self.horizontalLayout.addWidget(self.hdriList)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.custom = QtGui.QLabel(lazySiouxsie)
        self.custom.setObjectName("custom")
        self.horizontalLayout_3.addWidget(self.custom)
        self.custom_hdri = QtGui.QLineEdit(lazySiouxsie)
        self.custom_hdri.setObjectName("custom_hdri")
        self.horizontalLayout_3.addWidget(self.custom_hdri)
        self.browse_btn = QtGui.QPushButton(lazySiouxsie)
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout_3.addWidget(self.browse_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startLabel = QtGui.QLabel(lazySiouxsie)
        self.startLabel.setObjectName("startLabel")
        self.horizontalLayout_2.addWidget(self.startLabel)
        self.startFrame = QtGui.QSpinBox(lazySiouxsie)
        self.startFrame.setObjectName("startFrame")
        self.horizontalLayout_2.addWidget(self.startFrame)
        self.endLabel = QtGui.QLabel(lazySiouxsie)
        self.endLabel.setObjectName("endLabel")
        self.horizontalLayout_2.addWidget(self.endLabel)
        self.endFrame = QtGui.QSpinBox(lazySiouxsie)
        self.endFrame.setObjectName("endFrame")
        self.horizontalLayout_2.addWidget(self.endFrame)
        self.total_frames = QtGui.QLineEdit(lazySiouxsie)
        self.total_frames.setObjectName("total_frames")
        self.horizontalLayout_2.addWidget(self.total_frames)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.cancel_btn = QtGui.QPushButton(lazySiouxsie)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_4.addWidget(self.cancel_btn)
        self.spin_btn = QtGui.QPushButton(lazySiouxsie)
        self.spin_btn.setObjectName("spin_btn")
        self.horizontalLayout_4.addWidget(self.spin_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(lazySiouxsie)
        self.hdriList.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(lazySiouxsie)

    def retranslateUi(self, lazySiouxsie):
        lazySiouxsie.setWindowTitle(QtGui.QApplication.translate("lazySiouxsie", "Lazy Siouzsie", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setText(QtGui.QApplication.translate("lazySiouxsie", "Lazy Siouxsie", None, QtGui.QApplication.UnicodeUTF8))
        self.file_label.setText(QtGui.QApplication.translate("lazySiouxsie", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.hdri_label.setText(QtGui.QApplication.translate("lazySiouxsie", "HDRIs", None, QtGui.QApplication.UnicodeUTF8))
        self.custom.setText(QtGui.QApplication.translate("lazySiouxsie", "Custom HDRI", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_btn.setText(QtGui.QApplication.translate("lazySiouxsie", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.startLabel.setText(QtGui.QApplication.translate("lazySiouxsie", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.endLabel.setText(QtGui.QApplication.translate("lazySiouxsie", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_btn.setText(QtGui.QApplication.translate("lazySiouxsie", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.spin_btn.setText(QtGui.QApplication.translate("lazySiouxsie", "Spin It", None, QtGui.QApplication.UnicodeUTF8))

